version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: recyclecs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: C3pt
      POSTGRES_DB: recyclecs
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

volumes: {}
