@echo off
echo Reiniciando aplicacao...
echo Limpando cache...
npm cache clean --force
echo Instalando dependencias...
npm install --legacy-peer-deps
echo Construindo a aplicacao...
npm run build --legacy-peer-deps
echo Iniciando o servidor de desenvolvimento...
npm run dev 